### ISSUE TITLE
Commissioning

### ISSUE THREAD

**Issue by Informaticore** [HomeSmartMesh/sdk-hsm-sensortag#1]
To get a more easy plug-n-play solution we would need the commissioning been implemented for the sensor tag.

**Comment by wassfila** [comment]
This is done with 15b3c7c

I shifted the default config to be a joiner

https://github.com/HomeSmartMesh/sdk-hsm-sensortag/blob/15b3c7c2ed6fb304dae89fa50b9e004bac0a1587/samples/openthread_tag_sensors/prj.conf#L40

What I managed to get running before is this example with command line config on server side and cli as joiner

https://www.homesmartmesh.com/docs/networks/thread/#commissioning

now with the joiner as sensor tag, I did not manage to get it to run yet, I tried to use the web GUI on the server

This is the reference doc
https://openthread.io/guides/build/commissioning

**Comment by wassfila** [comment]
"joining" is the needed configuration for the device, "commissioning" is what is needed on the Boarder router side, it's quite easy, now also documented on the readme
https://github.com/HomeSmartMesh/sdk-hsm-sensortag/tree/main/samples/openthread_tag_sensors#usage
