### ISSUE TITLE
RGB LED Usage

### ISSUE THREAD

**Issue by Informaticore** [HomeSmartMesh/sdk-hsm-sensortag#2]
The new Hardware has a RGB LED but it is currently not used. We need to implement some easy Szenarios to use the RGB LED

Szenarios:

- **No Thread connection** :: blinks red shortly every 3s
- **Thread connected** :: Green for 3s

**Comment by wassfila** [comment]
The leds are already declared as leds and pwm leds, we can start with a simpler first blink on power on

https://github.com/HomeSmartMesh/sdk-hsm-sensortag/blob/15b3c7c2ed6fb304dae89fa50b9e004bac0a1587/boards/arm/nrf52840_sensortag/nrf52840_sensortag.dts#L27

I have an example on how to use leds with Zephyr from the HW repo with the old Zephyr platformio examples

https://github.com/HomeSmartMesh/nrf52_thread_sensortag/blob/a2b7dd8189ce723744c1acf6d6d30e3de5593727/firmware/04_dongle_pio_zephyr_blink/src/main.c#L45

**Comment by wassfila** [comment]
indeed, this is a vital feature for the Tag usability, after some experimentation with Thread Stack, here how we can take advantage of the led.

- as few states as possible not to confuse users
- use different colors but also different blink frequencies (color blind friendly)
- be low power friendly, think how long will the tag las if it is left blinking for weeks, e.g. slow down blinking, make the pulse shorter

It is also important for the development to be able to identify the state:
(note, I'm using Nordic's fork of Zephyr and openthread)
The roles are defined here : https://github.com/nrfconnect/sdk-openthread/blob/edc1a3fe2325428e7ff304ea3e92dba9da652c92/include/openthread/thread.h#L74

For the sensor tag, only those two roles are relevant
- disabled : after factory reset, when no network was joined
- detached : after having authenticated in a network but not yet joined, e.g. after restart out of network
- child : normal and expected operating modes

Now the led, might be needed to indicate other things like low battery, but I'll keep it out for the moment as we still don't know the range color mapping including temperature fluctuations

**Comment by wassfila** [comment]
# Startup
in normal operation when commissioned on first startup and wake up with available credentials

  hello                                hello
🔴 🟢 🔵 <-  3sec -> 🔴 🟢 🔵  => detached 🔵🔵 => child 🟢 <- 30 sec sleep - >🟢 <- 30 sec sleep - >🟢


# No Network
=> detached 🔵🔵  <-  sleep 40 sec - > => detached 🔵🔵  <-  sleep 40 sec - > => detached 🔵🔵  

# No Network after factory reset
=> Disabled  🔵🔵  <-  sleep 40 sec - > => Disabled 🔴🔴🔴 reboot

# Factory reset
- press both buttons after first hello signal and before second (within 3 seconds) for a quick reboot
- repeat quick reboot x2 times

press -> reboot  🔴🟢🔵<press> quick-reboot  🔴🟢🔵<press > quick-reboot  🔵 🔵 🔵  factory reset => reboot
